# Configuration file for deploying the renku chart on minikube
# against gitlab.com. We also need to configure the keycloak instance which is part
# of Renku to use gitlab.com as identity provider. See the developer docs
# (https://renku.readthedocs.io/en/latest/developer/example-configurations/gitlab.html)
# for instructions on how to use this values file.

variables:
  gitlabURL:          &gitlabURL           https://gitlab.com
  gitlabClientId:     &gitlabClientId      # Put Application Id here!
  gitlabClientSecret: &gitlabClientSecret  # Put Application Secret here!
  gitlabRegistryHost: &gitlabRegistryHost  registry.gitlab.com

global:
  gitlab:
    urlPrefix: ""

gitlab:
  enabled: false

notebooks:
  gitlab:
    url: *gitlabURL
    registry:
      host: *gitlabRegistryHost
  jupyterhub:
    hub:
      extraEnv:
        GITLAB_URL: *gitlabURL
    auth:
      gitlab:
        clientId: *gitlabClientId
        clientSecret: *gitlabClientSecret

graph:
  gitlab:
    url: *gitlabURL
  knowledgeGraph:
    services:
      renku:
        # At the moment the url matches 'gitlab.url' but it should be the Renku UI url
        # once https://github.com/SwissDataScienceCenter/renku-python/issues/554 issue is played
        url: *gitlabURL

gateway:
  gitlabUrl: *gitlabURL
  gitlabClientId: *gitlabClientId
  gitlabClientSecret: *gitlabClientSecret
