---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gitlab-password: {{ required "Fill in .Values.password with `openssl rand -hex 16`" .Values.password | b64enc | quote }}
  postgres-password: {{ required "Fill in .Values.global.gitlab.postgresPassword with `openssl rand -hex 16`" .Values.global.gitlab.postgresPassword | b64enc | quote }}
  gitlab-client-secret: {{ required "Fill in .Values.global.gitlab.clientSecret with `uuidgen -r`" .Values.global.gitlab.clientSecret | b64enc | quote }}
  shared-runners-registration-token: {{ required "Fill in .Values.sharedRunnersRegistrationToken with `openssl rand -hex 32`" .Values.sharedRunnersRegistrationToken | b64enc | quote }}

{{- if .Values.lfsObjects.enabled }}
  gitlab-lfs-connection: {{ .Values.lfsObjects.connection | b64enc | quote }}
{{- end }}

{{- if .Values.registry.storage }}
  gitlab-registry-storage: {{ .Values.registry.storage | b64enc | quote }}
{{- end }}
