{{- if not (empty .Values.ssh.nodePortService) -}}
{{- if .Values.ssh.nodePortService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}-ssh
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 22
      nodePort: {{ .Values.ssh.nodePortService.nodePort }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "gitlab.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
{{- end -}}
