---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ui.fullname" . }}-init
  labels:
    app: {{ template "ui.name" . }}
    chart: {{ template "ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  init.sh: |-
    set -ex
    apt-get update -y
    apt-get install -y curl

    until sleep 1; curl --retry-max-time 1 http://{{ template "gitlab.fullname" . }}/help; do
        echo waiting for gitlab
    done

    psql -v ON_ERROR_STOP=1 -h {{ template "postgresql.fullname" . }} --username "$POSTGRES_USER" \
      -d $POSTGRES_DATABASE \ <<-EOSQL
        DELETE FROM oauth_applications WHERE uid='renga-ui';
        INSERT INTO oauth_applications (name, uid, scopes, redirect_uri, secret, trusted)
        VALUES ('renga-ui', 'renga-ui', 'api read_user', 'http://{{ .Values.global.renga.domain }}/login/redirect/gitlab', 'no-secret-needed', 'true');
    EOSQL
