apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: {{ template "ui.name" . }}
    chart: {{ template "ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ui.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: postgres:9.6
          command: ['sh', '/scripts/init.sh']
          volumeMounts:
          - name: init
            mountPath: /scripts
            readOnly: true
          env:
          - name: POSTGRES_DATABASE
            value: {{ .Values.global.gitlab.postgresDatabase }}
          - name: POSTGRES_USER
            value: {{ .Values.global.gitlab.postgresUser }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "gitlab.fullname" . }}
                key: postgres-password
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: GITLAB_URL
              value: "{{ template "http" . }}://{{ .Values.global.renga.domain }}/gitlab"
            - name: BASE_URL
              value: "{{ template "http" . }}://{{ .Values.global.renga.domain }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: init
          configMap:
            name: {{ template "ui.fullname" . }}-init
          defaultMode: 0777
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
