# -*- coding: utf-8 -*-
#
# Copyright 2017 Swiss Data Science Center
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

notifications:
  email: false

sudo: required

services:
  - docker

branches:
  only:
    - master

language: python

matrix:
  fast_finish: true

python:
  - "3.6"

before_install:
  - pip install -r requirements-test.txt

install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY
  - ./travis-install.sh

before_script:
  - docker-compose up -d
  - travis_retry docker run --network renga_default --rm
    --link keycloak
    --link deployer
    --link explorer
    --link graph-mutation
    --link graph-navigation
    --link graph-typesystem
    --link resource-manager
    --link storage
    -e TARGETS=keycloak:8080,deployer:5000,explorer:9000,graph-mutation:9000,graph-navigation:9000,graph-typesystem:9000,resource-manager:9000,storage:9000
    -e TIMEOUT=60
    waisbrot/wait

script:
  - pytest -v
