# -*- coding: utf-8 -*-
#
# Copyright 2017-2018 - Swiss Data Science Center (SDSC)
# A partnership between École Polytechnique Fédérale de Lausanne (EPFL) and
# Eidgenössische Technische Hochschule Zürich (ETHZ).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required
dist: trusty

notifications:
  email: false

services:
  - docker

env:
  global:
    - DOCKER_HOST="tcp://86.119.32.161:443"
    - DOCKER_TLS_VERIFY=1
    - secure: "SO0R2rBsYb8cazUp+XkvaKnKS5woJjkny3DWPnB3IudHx1nbx8AvvoOlz64v9/4ajluVBapdJFqELdGMzpGUgZBKvHZRCgx+TC44P/wyWdTYY8iYCoJej0dNXBnmhtTxezMazuq0WcjzUdN7FMSaN12JFa7VLMiHb0I9VGCc0+x0ksgH2CAZhrOHkWpgnRxoqAzTSbNFMRzxwerQrIb4Uar1GKf4ppw05xEEoufcqK8P4uGm8d6x28Rw26YqLtw4DQPbf7SzCmg3qaWIteSFnGWgoMkOGgJU1/DbSNxn8wO+EQ8nW75JrnR2H9y3SW0hfl4SxBosQT4rl32HZMcJJlUMawim9yuooxTm6uuMgAxzwMByUGTTgW3gR2fGo3jWrpJg+Y941vwAITa7uyAOM72EpiHcH0Ttb5a1YDhgu6kyGl8i0y/lGEx5I4w9cc/nG07EJWuHHpOfrUI7hFxxXfpHOiS6/zuPmoeWLWg61nBAZRbRFAwKuU+tAd5roeYFU7gC/yZ/DAg7/KXLeulLIazSaEUvKE2Fo46YjI0ZL4Od7B6fFQh/w16cIVhHC+jE+CXkisvTT2m5crkv+Y9sjHxKH4pgxQhz3TmfLco7Q4tUXUvPUG5glytXMF4wz7pJu9DoYyopL0gzKdq3aDDRzJalP9rTPnjUU6PbCaf8DXw="
#     - HELM_URL=https://storage.googleapis.com/kubernetes-helm
#     - HELM_TGZ=helm-v2.9.1-linux-amd64.tar.gz

git:
  depth: false

addons:
  apt:
    packages:
      - git
      - jq

branches:
  only:
    - master

language: python

matrix:
  fast_finish: true

python:
  - "3.6"

before_install:
  - sudo apt-get install enchant shellcheck
  - echo $maxikube_secret_pass | gpg --passphrase-fd 0 maxikube_secrets.tar.gpg
  - tar xvf maxikube_secrets.tar
  - export DOCKER_CERT_PATH="$PWD/docker-certs"
  - mkdir -p ~/.kube
  - mv admin.conf ~/.kube/config

install:
  - ./scripts/travis-install.sh

before_script:
  - ./scripts/travis-before-script.sh

script:
  - ./scripts/travis-build.sh
  - make test
  # TODO - helm lint charts/renku -f charts/minikube-values.yaml --set renku.domain=renku.build

# before_deploy:
#   # install chartpress
#   - pip install -U pip
#   - pip install -e git+https://github.com/jirikuncar/chartpress#egg=chartpress
#   # install Helm
#   - wget -q ${HELM_URL}/${HELM_TGZ}
#   - tar xzfv ${HELM_TGZ}
#   - PATH=`pwd`/linux-amd64/:$PATH
#   - helm init --client-only
#
# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: bash scripts/travis-deploy.sh
#     on:
#       branch: master
