## Default values file + full documentation at https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml
global:
  edition: ce
  hosts:
    domain: glnative.dev.renku.ch
    externalIP: 86.119.39.201
    https: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-production
    configureCertmanager: false
    enabled: true
    tls:
      enabled: true
    # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#configure-ingress-settings
    # Using external cert-manager requires to define the secrets, otherwise this secret needs to be a wildcard
    #  secretName: gitlab-glnative-dev-renku-ch-tls
  time_zone: CET
  appConfig:
    # OmniAuth Settings
    # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#omniauth
    # Openid connect reference
    # https://docs.gitlab.com/ee/administration/auth/oidc.html
    omniauth:
      enabled: true
      ## enabled: false
      autoSignInWithProvider: openid_connect
      # allowSingleSignOn: true
      # CAUTION!
      # This allows users to sign in without having a user account first. Define the allowed providers
      # using an array, for example, ["saml", "twitter"], or as true/false to allow all providers or none.
      # User accounts will be created automatically when authentication was successful.
      allowSingleSignOn: ['openid_connect']
      blockAutoCreatedUsers: false
      providers:
       - secret: renku-oauth-provider
         key: provider
    lfs:
      #  directUpload: false
      #  backgroundUpload: true
      enabled: true
      proxy_download: false
      bucket: glnative-dev-lfs-objects
      connection:
        secret: glnative-lfs-connection
        key: openstack-connection
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab:
  webservice:
    ingress:
      tls:
        secretName: gitlab-glnative-dev-renku-ch-tls
registry:
  ingress:
    tls:
      secretName: registry-gl-native-dev-renku-ch-tls
minio:
  ingress:
    tls:
      secretName: minio-gl-native-dev-renku-ch-tls
