dependencies:
- name: renku-core
  alias: core
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.10.5
- name: renku-ui
  alias: ui
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.11.0-dacfd4b
- name: renku-notebooks
  alias: notebooks
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.7.5-4aaf203
- name: renku-gateway
  alias: gateway
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.8.1-4a36b1e
- name: gitlab
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.5.2
  condition: gitlab.enabled
- name: renku-graph
  alias: graph
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 1.2.2
  condition: graph.enabled
- name: postgresql
  version: 0.14.4
  repository: "@stable"
  condition: postgresql.enabled
- name: keycloak
  version: 4.10.1
  repository: "@stable"
  condition: keycloak.enabled
- name: minio
  version: 1.6.0
  repository: "@stable"
  condition: minio.enabled
