dependencies:
- name: renku-ui
  alias: ui
  version: "0.1.0-0b58060"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
- name: renku-notebooks
  alias: notebooks
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: "0.1.0-1d7b5db"
- name: renku-gateway
  alias: gateway
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: "0.1.0-08f7296"
- name: jupyterhub
  version: "v0.7-51c7a58"
  repository: "https://jupyterhub.github.io/helm-chart"
- name: postgresql
  version: 0.14.4
  repository: "@stable"
- name: gitlab
  version: "0.1.0-bb3b9b6"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  condition: gitlab.enabled
- name: redis
  version: "0.1.0-b00c63d"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  condition: gitlab.enabled
- name: keycloak
  version: 3.2.0
  repository: "@stable"
  condition: keycloak.enabled
- name: minio
  version: 1.6.0
  repository: "@stable"
  condition: minio.enabled
