---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "logstash.fullname" . }}
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.containerPort }}
    protocol: {{ $port.protocol }}
    targetPort: {{ $port.containerPort }}
  {{- end }}
  selector:
    app: {{ template "logstash.name" . }}
    release: {{ .Release.Name }}
