charts:
  - name: gitlab
    imagePrefix: renku/
    repo:
      git: SwissDataScienceCenter/helm-charts
      published: https://swissdatasciencecenter.github.io/helm-charts
    paths:
      - ./gitlab
  - name: renku
    resetTag: latest
    imagePrefix: renku/
    repo:
      git: SwissDataScienceCenter/helm-charts
      published: https://swissdatasciencecenter.github.io/helm-charts
    paths:
      - .
      - ../services/apispec
      - ../tests
      - ../scripts/init-realm
    images:
      apispec:
        contextPath: ../services/apispec
        dockerfilePath: ../services/apispec/Dockerfile
        valuesPath: apispec.image
        paths:
          - ../services/apispec
      tests:
        contextPath: ../tests
        dockerfilePath: ../tests/Dockerfile
        valuesPath: tests.image
        paths:
          - ../tests
      init-realm:
        contextPath: ../scripts/init-realm
        dockerfilePath: ../scripts/init-realm/Dockerfile
        valuesPath: keycloak.initRealm.image
        paths:
          - ../scripts/init-realm
