#
# Configuration file for deploying the renga chart on minikube
#

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: false
  hosts:
  - ""

storage:
  adminToken: changemechangeme
  appSecret: changemechangeme
  env:
    STORAGE_BACKEND_LOCAL_ENABLED: "true"
    STORAGE_BACKEND_LOCALGIT_ENABLED: "true"
    STORAGE_BACKEND_GITLAB_ENABLED: "true"
    RENGA_STORAGE_DEFAULT_LFS_BACKEND: "local"
