#
# Configuration file for deploying the renga chart on minikube
#

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: false
  hosts:
  - ""
