---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "elasticsearch.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "elasticsearch.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "elasticsearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
