---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  elasticsearch.yml: |-
    cluster.name: {{ .Values.cluster.name }}

    node.data: ${NODE_DATA:true}
    node.master: ${NODE_MASTER:true}
    node.ingest: ${NODE_INGEST:true}
    node.name: ${HOSTNAME}

    network.host: 0.0.0.0

    # cloud:
    #   kubernetes:
    #     service: ${SERVICE}
    #     namespace: ${KUBERNETES_NAMESPACE}

    bootstrap.memory_lock: ${BOOTSTRAP_MEMORY_LOCK:false}

    discovery:
      zen:
        # hosts_provider: kubernetes
        ping.unicast.hosts:
        - ${SERVICE}
        minimum_master_nodes: ${MINIMUM_MASTER_NODES:2}

    processors: ${PROCESSORS:}
