{{- if not (empty .Values.registry.exposedAs) -}}
{{- if eq .Values.registry.exposedAs "NodePort" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}-registry
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: 10.100.123.45
  type: NodePort
  ports:
    - port: 8105
      nodePort: 30105
      targetPort: registry
      protocol: TCP
      name: registry
  selector:
    app: {{ template "gitlab.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
{{- end -}}
