apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "gitlab.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gitlab.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: gitlab-password
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: "long-and-random-alpha-numeric-string"
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: "long-and-random-alpha-numeric-string"
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: "long-and-random-alpha-numeric-string"
        - name: GITLAB_HOST
          value: {{ .Values.hostname | default "localhost" }}
        - name: GITLAB_RELATIVE_URL_ROOT
          value: /gitlab
        - name: DB_HOST
          value: "{{ template "postgresql.fullname" . }}"
        - name: DB_NAME
          value: {{ .Values.global.gitlab.postgresDatabase }}
        - name: DB_USER
          value: {{ .Values.global.gitlab.postgresUser }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab.fullname" . }}
              key: postgres-password
        - name: REDIS_HOST
          value: "{{ template "redis.fullname" . }}"
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: registry
          containerPort: 8105
        livenessProbe:
          httpGet:
            path: /gitlab/help
            port: http
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 600
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /gitlab/help
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
