---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "storage.fullname" . }}-init
  labels:
    app: {{ template "storage.name" . }}
    chart: {{ template "storage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  init.sh: |-
    set -ex
    apt-get update -y
    apt-get install -y curl

    until sleep 5; curl --retry-max-time 1 http://{{ template "gitlab.fullname" . }}/help; do
        echo waiting for gitlab
    done

    psql -v ON_ERROR_STOP=1 -h {{ template "postgresql.fullname" . }} --username "$POSTGRES_USER" \
      -d $POSTGRES_DATABASE \ <<-EOSQL
        DELETE FROM personal_access_tokens WHERE user_id='1' AND name='managed storage token';
        INSERT INTO personal_access_tokens ( user_id, token, name, revoked, expires_at, created_at, updated_at, scopes, impersonation)
        VALUES ( '1', '$(GITLAB_TOKEN)', 'managed storage token', 'f', NULL, NOW(), NOW(), E'--- \n- api\n- read_user\n- sudo\n- read_registry', 'f');
    EOSQL
