{{ if and .Values.global.anonymousSessions.enabled .Values.global.anonymousSessions.autoCreateTmpNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}-tmp
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ end }}
