---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-gitlab-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.gateway.gitlabClientSecret.value .Values.global.gateway.gitlabClientSecret.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  gateway-gitlab-client-secret: {{ default (randAlphaNum 64) .Values.global.gateway.gitlabClientSecret.value | b64enc | quote }}
