---
{{- if .Values.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-gitlab-sudo
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.gitlab.sudoToken.value .Values.global.gitlab.sudoToken.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  gitlab-sudo-token: {{ default (randAlphaNum 64) .Values.global.gitlab.sudoToken.value | b64enc | quote }}
{{- end }}
