---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-graph-token-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.graph.tokenRepository.postgresPassword.value .Values.global.graph.tokenRepository.postgresPassword.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  graph-tokenRepository-postgresPassword: {{ default (randAlphaNum 64) .Values.global.graph.tokenRepository.postgresPassword.value | b64enc | quote }}
