{{- if .Values.ingress.enabled -}}
{{- $keycloakEnabled := .Values.keycloak.enabled -}}
{{- $keycloakFullname := include "keycloak.fullname" . -}}
{{- $keycloakServicePort := .Values.keycloak.keycloak.service.port -}}
{{- $gitlabEnabled := .Values.gitlab.enabled -}}
{{- $gitlabFullname := include "gitlab.fullname" . -}}
{{- $gitlabServicePort := 80 -}}
{{- $uiFullname := include "ui.fullname" . -}}
{{- $uiServicePort := .Values.ui.service.port -}}
{{- $gatewayFullname := include "gateway.fullname" . -}}
{{- $gatewayServicePort := .Values.gateway.service.port -}}
{{- $graphEnabled := .Values.graph.enabled -}}
{{- $webhookServiceFullname := include "webhookService.fullname" . -}}
{{- $knowledgeGraphFullname := include "knowledgeGraph.fullname" . -}}
{{- if $graphEnabled }}
{{- $jenaFullname := include "jena.fullname" . -}}
{{- $jenaServicePort := .Values.graph.jena.service.port -}}
{{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      {{- if $keycloakEnabled }}
      - path: /auth
        backend:
          serviceName: {{ $keycloakFullname }}-http
          servicePort: {{ $keycloakServicePort }}
      {{- end }}
      {{- if $gitlabEnabled }}
      - path: /gitlab
        backend:
          serviceName: {{ $gitlabFullname }}
          servicePort: {{ $gitlabServicePort }}
      {{- end }}
      - path: /jupyterhub
        backend:
          serviceName: proxy-public
          servicePort: 8000
      - path: /api
        backend:
          serviceName: {{ $gatewayFullname }}
          servicePort: {{ $gatewayServicePort }}
      - path: /
        backend:
          serviceName: {{ $uiFullname }}
          servicePort: {{ $uiServicePort }}
      {{- if $graphEnabled }}
      - path: /webhooks/events
        backend:
          serviceName: {{ $webhookServiceFullname }}
          servicePort: 80
      - path: /knowledge-graph
        backend:
          serviceName: {{ $knowledgeGraphFullname }}
          servicePort: 80
      {{- end }}
  {{- end }}
{{- end }}
