---
apiVersion: v1
kind: Secret
metadata:
  name: renku-jupyterhub-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.jupyterhub.postgresPassword.value .Values.global.jupyterhub.postgresPassword.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  jupyterhub-postgres-password: {{ default (randAlphaNum 64) .Values.global.jupyterhub.postgresPassword.value | b64enc | quote }}
