---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-jupyterhub-gitlab
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.notebooks.jupyterhub.auth.gitlab.clientSecret.value .Values.notebooks.jupyterhub.auth.gitlab.clientSecret.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  jupyterhub-auth-gitlab-client-secret: {{ default (randAlphaNum 64) .Values.notebooks.jupyterhub.auth.gitlab.clientSecret.value | b64enc | quote }}
