---
{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-password-secret
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.keycloak.password.value .Values.global.keycloak.password.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  keycloak-password: {{ default (randAlphaNum 64) .Values.global.keycloak.password.value | b64enc | quote }}
{{- end }}
