---
{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-keycloak
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.keycloak.secret.generate .Values.keycloak.keycloak.password .Values.global.keycloak.postgresPassword -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  keycloak-password: {{ default (randAlphaNum 64) .Values.keycloak.keycloak.password | b64enc | quote }}
  keycloak-postgres-password: {{ default (randAlphaNum 64) .Values.global.keycloak.postgresPassword | b64enc | quote }}
  renku-realm.json: {{ include "renku.keycloak.realm" . | indent 4  | b64enc | quote }}
{{- end }}
