apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-postgres"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-post-install-postgres"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: init-databases
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          command: ["/bin/bash", "/scripts/init-postgres.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: passwords
              mountPath: /passwords
              readOnly: true
          env:
          - name: PGDATABASE
            value: {{ .Values.postgresql.postgresqlDatabase }}
          - name: PGUSER
            value: {{ .Values.postgresql.postgresqlUser }}
          - name: PGHOST
            value: {{ template "postgresql.fullname" . }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "postgresql.fullname" . }}
                key: postgresql-password
      volumes:
        - name: scripts
          configMap:
            name: {{ template "renku.fullname" . }}
        - name: passwords
          secret:
            secretName: {{ template "renku.fullname" . }}
