apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-postgres"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-post-install-postgres"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
        - name: init-databases
          image: "{{ .Values.postgresql.image }}:{{ .Values.postgresql.imageTag }}"
          command: ["/bin/bash", "/scripts/init-postgres.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: keycloak-postgres
              mountPath: /keycloak-postgres
              readOnly: true
            - name: gitlab-sudo
              mountPath: /gitlab-sudo
              readOnly: true
            - name: gitlab-postgres
              mountPath: /gitlab-postgres
              readOnly: true
            - name: jupyterhub-postgres
              mountPath: /jupyterhub-postgres
              readOnly: true
            - name: graph-db-postgres
              mountPath: /graph-db-postgres
              readOnly: true
          env:
          - name: PGDATABASE
            value: {{ .Values.postgresql.postgresDatabase }}
          - name: PGUSER
            value: {{ .Values.postgresql.postgresUser }}
          - name: PGHOST
            value: {{ template "postgresql.fullname" . }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "postgresql.fullname" . }}
                key: postgres-password
      volumes:
        - name: scripts
          configMap:
            name: {{ template "renku.fullname" . }}
        - name: keycloak-postgres
          secret:
            secretName: {{ template "renku.fullname" . }}-keycloak-postgres
        - name: gitlab-sudo
          secret:
            secretName: {{ template "renku.fullname" . }}-gitlab-sudo
        - name: gitlab-postgres
          secret:
            secretName: {{ template "renku.fullname" . }}-gitlab-postgres
        - name: jupyterhub-postgres
          secret:
            secretName: {{ template "renku.fullname" . }}-jupyterhub-postgres
        - name: graph-db-postgres
          secret:
            secretName: {{ template "renku.fullname" . }}-graph-db-postgres
