{{- if .Values.gitlab.registry.enabled -}}
{{- $auth := printf "root:%s" .Values.global.gitlab.sudoToken | b64enc -}}
{{- $secret := printf "{\"auths\":{\"%s\":{\"username\":\"root\",\"password\":\"%s\",\"email\":\"root@example.com\",\"auth\":\"%s\"}}}" .Values.gitlab.registry.externalUrl .Values.global.gitlab.sudoToken $auth -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ template "renku.fullname" . }}-registry
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ $secret | b64enc | quote }}
{{- end -}}
