---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.gitlab.enabled }}
  {{- if .Values.global.gitlab.sudoToken }}
  gitlab-sudo-token: {{ .Values.global.gitlab.sudoToken | b64enc | quote }}
  {{- else }}
  gitlab-sudo-token: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  gitlab-postgres-password: {{ .Values.global.gitlab.postgresPassword | b64enc | quote }}
{{- end }}
{{- if .Values.keycloak.enabled }}
  keycloak-password: {{ .Values.keycloak.keycloak.password | b64enc | quote }}
  keycloak-postgres-password: {{ .Values.global.keycloak.postgresPassword | b64enc | quote }}
  renku-realm.json: {{ include "renku.keycloak.realm" . | indent 4  | b64enc | quote }}
{{- end }}
  jupyterhub-postgres-password: {{ .Values.global.jupyterhub.postgresPassword | b64enc | quote }}
