---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.gitlab.enabled }}
  gitlab-sudo-token: {{ required "Fill in .Values.global.gitlab.sudoToken with `openssl rand -hex 32`" .Values.global.gitlab.sudoToken | b64enc | quote }}
  gitlab-postgres-password: {{ required "Fill in .Values.global.gitlab.postgresPassword with `openssl rand -hex 32`" .Values.global.gitlab.postgresPassword | b64enc | quote }}
{{- end }}

{{- if .Values.keycloak.enabled }}
  keycloak-password: {{ required "Fill in .Values.keycloak.keycloak.password with `openssl rand -hex 16`" .Values.keycloak.keycloak.password | b64enc | quote }}
  keycloak-postgres-password: {{ required "Fill in .Values.global.keycloak.postgresPassword with `openssl rand -hex 16`" .Values.global.keycloak.postgresPassword | b64enc | quote }}
  renku-realm.json: {{ include "renku.keycloak.realm" . | indent 4  | b64enc | quote }}
{{- end }}

  jupyterhub-postgres-password: {{ required "Fill in .Values.global.jupyterhub.postgresPassword with `openssl rand -hex 16`" .Values.global.jupyterhub.postgresPassword | b64enc | quote }}

{{- if .Values.tests.users_json }}
  users.json: {{ .Values.tests.users_json | toJson | b64enc | quote }}
{{- end }}

  jupyterhub-auth-gitlab-client-secret: {{ required "Fill in .Values.notebooks.jupyterhub.auth.gitlab.clientSecret with `openssl rand -hex 32`" .Values.notebooks.jupyterhub.auth.gitlab.clientSecret | b64enc | quote }}
  gateway-gitlab-client-secret: {{ required "Fill in .Values.global.gateway.gitlabClientSecret with `openssl rand -hex 32`" .Values.global.gateway.gitlabClientSecret | b64enc | quote }}

tokenRepository-postgresPassword: {{ required "Fill in .Values.global.graph.tokenRepository.postgresPassword with `openssl rand -hex 16`" .Values.global.graph.tokenRepository.postgresPassword | b64enc | quote }}
