---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.global.gitlab.sudoToken }}
  gitlab-sudo-token: {{ .Values.global.gitlab.sudoToken | b64enc | quote }}
{{- else }}
  gitlab-sudo-token: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
  keycloak-password: {{ .Values.global.keycloak.postgresPassword | b64enc | quote }}
  gitlab-password: {{ .Values.global.gitlab.postgresPassword | b64enc | quote }}
  jupyterhub-password: {{ .Values.global.jupyterhub.postgresPassword | b64enc | quote }}
