---
{{- if .Values.keycloak.enabled }}
{{- $postgresqlFullname := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: renku-keycloak-postgres
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.keycloak.postgresPassword.value .Values.global.keycloak.postgresPassword.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  DB_ADDR: {{ $postgresqlFullname | b64enc | quote }}
  DB_DATABASE: {{ .Values.global.keycloak.postgresDatabase | b64enc | quote }}
  DB_USER: {{ .Values.global.keycloak.postgresUser | b64enc | quote }}
  DB_PASSWORD: {{ default (randAlphaNum 64) .Values.global.keycloak.postgresPassword.value | b64enc | quote }}
{{- end }}
