---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}-postgresql-password
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
    postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- if .Values.global.gitlab.enabled }}
    gitlab-postgres-password: {{ default (randAlphaNum 64) .Values.global.gitlab.postgresPassword.value | b64enc | quote }}
{{- end }}
{{- end }}
