---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renku.fullname" . }}
  labels:
    app: {{ template "renku.name" . }}
    chart: {{ template "renku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.keycloak.enabled }}
  keycloak-username: {{ required "Fill in .Values.keycloak.keycloak.username" .Values.keycloak.keycloak.username | b64enc | quote }}
  clients: {{ include "renku.keycloak.clients" .  | b64enc | quote }}
  users: {{ include "renku.keycloak.users" . | b64enc | quote }}
{{- end }}

{{- if .Values.tests.users_json }}
  users.json: {{ .Values.tests.users_json | toJson | b64enc | quote }}
{{- end }}

  jupyterhub-auth-gitlab-client-secret: {{ required "Fill in .Values.notebooks.jupyterhub.auth.gitlab.clientSecret with `openssl rand -hex 32`" .Values.notebooks.jupyterhub.auth.gitlab.clientSecret | b64enc | quote }}
  gateway-gitlab-client-secret: {{ required "Fill in .Values.global.gateway.gitlabClientSecret with `openssl rand -hex 32`" .Values.global.gateway.gitlabClientSecret | b64enc | quote }}
