---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitlab.fullname" . }}-config
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  gitlab.rb: |-
{{ include "gitlab.config" . | indent 4 }}
