{{- if .Values.service.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if.Values.service.metrics.annotations }}
  annotations:
{{ toYaml .Values.service.metrics.annotations | indent 4 }}
{{- end }}
  name: {{ template "gitlab.fullname" . }}-metrics
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ template "gitlab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "gitlab.name" . }}
    release: {{ .Release.Name }}
{{- end }}
