---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.password }}
  keycloak-password: {{ .Values.password | b64enc | quote }}
{{- else }}
  keycloak-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- if .Values.global.keycloak.postgresPassword }}
  postgres-password: {{ .Values.global.keycloak.postgresPassword | b64enc | quote }}
{{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
