name: Deploy Renku

on:
  push:
    paths:
    - charts/**
    branches:
    - master

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@v0.2.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  github-env:
    runs-on: ubuntu-latest
    steps:
    - name: get environment
      run: env
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy master to dev
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_KUBECONFIG }}
        CD_VALUES: ${{ secrets.CD_VALUES }}
      with:
        kubectl: 1.16.2
        helm: 2.16.1
        command: |
          set -x
          echo "$RENKUBOT_KUBECONFIG" > renkubot-kube.config
          helm init --client-only
          helm repo add renku https://swissdatasciencecenter.github.io/helm-charts/
          helm repo add gitlab https://charts.gitlab.io/
          helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
          rm -rf charts/renku/charts
          helm dependency update charts/renku
          printf "%s" "$CD_VALUES" > cd_values.yaml
          helm upgrade --install renku \
                      --namespace renku \
                      -f cd_values.yaml \
                      --timeout 1800 charts/renku \
                      --cleanup-on-fail
