name: Deploy dev

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@v0.2.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        version: 3.7
    - name: Install deploy dependencies
      run: scripts/travis-install.sh
    - name: configure k8s
      env:
        RENKUBOT_KUBECONFIG_GPG: ${{ secrets.RENKUBOT_KUBECONFIG_GPG }}
        KUBECONFIG: renkubot-kube.config
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$RENKUBOT_KUBECONFIG_GPG" \
            --output renkubot-kube.config scripts/renkubot-kube.config.gpg
        kubectl -n renku get pods
