name: Deploy dev

on:
  push:
    paths:
    - charts/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@v0.2.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        version: 3.7
    - name: Install deploy dependencies
      run: scripts/travis-install.sh
    - name: configure k8s
      env:
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_KUBECONFIG }}
        ROK_CD_VALUES: ${{ secrets.ROK_CD_VALUES }}
      run: |
        echo "$RENKUBOT_KUBECONFIG" > renkubot-kube.config
        helm init --client-only
        helm repo add renku https://swissdatasciencecenter.github.io/helm-charts/
        helm repo add gitlab https://charts.gitlab.io/
        helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
        cd charts
        rm -rf renku/charts
        helm dependency update renku
        printf "%s" "$ROK_CD_VALUES" > rok_cd_values.yaml
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y
        cat rok_cd_values.yaml | yq r - notebooks.jupyterhub.proxy.secretToken
        helm upgrade --install rok-cd-renku \
                     --namespace rok \
                     -f rok_cd_values.yaml \
                     --timeout 1800 ./renku \
                     --cleanup-on-fail
