name: Teardown PR
on:
  pull_request:
    types: [closed]

jobs:
  github-env:
    runs-on: ubuntu-latest
    steps:
    - name: get environment
      run: env
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
    - uses: docker://alpine/k8s:1.16.8
      name: k8s teardown
      env:
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_KUBECONFIG }}
        RENKU_RELEASE: "ci-${{ github.event.number }}-renku"
        RENKU_NAMESPACE: "ci-${{ github.event.number }}-renku"
      with:
        command: |
          echo "$RENKUBOT_KUBECONFIG" > renkubot-kube.config
          chmod 400 renkubot-kube.config
          kubectl delete ns $RENKU_NAMESPACE
          kubectl delete ns $RENKU_NAMESPACE-tmp
    - name: gitlab teardown
      env:
        GITLAB_TOKEN: ${{ secrets.DEV_GITLAB_TOKEN }}
        RENKU_RELEASE: "ci-${{ github.event.number }}-renku"
      run: |
        apps=$(curl -s https://dev.renku.ch/gitlab/api/v4/applications -H "private-token: ${GITLAB_TOKEN}" | jq -r ".[] | select(.application_name == \"${RENKU_RELEASE}\") | .id")
        for app in $apps
        do
          curl -X DELETE https://dev.renku.ch/gitlab/api/v4/applications/${app} -H "private-token: ${GITLAB_TOKEN}"
        done
