name: test renku deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: renku build and deploy
      uses: ./actions/deploy-renku
      env:
        renku_core: "@v0.11.0"
