name: Test dev values

on: [push]

jobs:
  github-env:
    runs-on: ubuntu-latest
    steps:
    - name: get environment
      run: env

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy master to dev
      uses: stefanprodan/kube-tools@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_KUBECONFIG }}
        RENKUBOT_GPG_PASSPHRASE: ${{ secrets.RENKUBOT_GPG_PASSPHRASE }}
        RENKUBOT_GPG_PRIVATE: ${{ secrets.RENKUBOT_GPG_PRIVATE }}
        OPS_GPG_KEYS: ${{ secrets.OPS_GPG_KEYS }}
        CD_VALUES: ${{ secrets.CD_VALUES }}
        RENKUBOT_OPSDEV_TOKEN: ${{ secrets.RENKUBOT_OPSDEV_TOKEN }}
      with:
        kubectl: 1.16.2
        helm: 2.16.1
        command: |
          echo "$RENKUBOT_GPG_PRIVATE" > renkubot-privatekey.asc
          gpg --batch --yes --passphrase="$RENKUBOT_GPG_PASSPHRASE" --import renkubot-privatekey.asc
          printf "%s" "$OPS_GPG_KEYS" > ops.gpg.pub
          gpg --import ops.gpg.pub
          export keys=`gpg --list-keys`
          echo "::warning file=app.js,line=1,col=5::BEFORE $keys"
          #for fpr in $(gpg --list-keys --with-colons  | awk -F: '/fpr:/ {print $10}' | sort -u); do  echo -e "5\ny\n" |  gpg --command-fd 0 --expert --edit-key $fpr trust; done
          export tty=`ls /dev/t*`
          echo "::warning file=app.js,line=1,col=5::BEFORE trusting one key $tty"
          echo -e "5\ny\n" |  gpg --command-fd 0 --expert --edit-key 2E8E3E6447725A15025BD90E859123913F532F3E trust
          export keys=`gpg --list-keys`
          echo "::warning file=app.js,line=1,col=5::AFTER $keys"

          curl -sL https://github.com/mozilla/sops/releases/download/v3.5.0/sops-v3.5.0.linux -o ./sops &&  chmod +x ./sops
          mv ./sops /usr/local/bin/sops
          git clone https://RenkuBot:${RENKUBOT_OPSDEV_TOKEN}@github.com/SwissDataScienceCenter/ops-dev.renku.ch.git
          cd ops-dev.renku.ch
          make decrypt
          make values
          cd ..
          cp ops-dev.renku.ch/renku-values.yaml cd_values.yaml
          rm -fr ops-dev.renku.ch

          echo "$RENKUBOT_KUBECONFIG" > renkubot-kube.config
          helm init --client-only
          helm repo add renku https://swissdatasciencecenter.github.io/helm-charts/
          helm repo add gitlab https://charts.gitlab.io/
          helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
          rm -rf charts/renku/charts
          helm dependency update charts/renku
